import { Inter } from "next/font/google";
import { Header } from "./Header";

import "./globals.css";
import Navigation from "./Navigation";
import NavigationLink from "./NavigationLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-surface text-on-surface">
          <div className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0">
            <Header>
              <Navigation>
                <NavigationLink href="/">Home</NavigationLink>
                <NavigationLink href="/about">About</NavigationLink>
                <NavigationLink href="/eula">Eula</NavigationLink>
                <NavigationLink href="/contact">Contact</NavigationLink>
              </Navigation>
            </Header>

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
