import { Inter } from "next/font/google";

import "./globals.css";
import Layout from "./Root";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Root({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="ltr">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
