import { Inter } from "next/font/google";


import Root from "./.Root";
import { Meta, Links, Outlet, ScrollRestoration, Scripts, MetaFunction } from "@remix-run/react";

import "./globals.css";


export const meta = (()=>[{
  title: "Create Next App",
  description: "Generated by create next app",
}]) satisfies MetaFunction;

export default function Layout() {
  return (
    <html lang="en" dir="ltr">
      <head>
          <meta charSet="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <Meta />
				<Links />
   </head>

      <body>
        <Root>  <Outlet></Outlet></Root>
      
  <ScrollRestoration />
  <Scripts />
      </body>
    </html>
  );
}
