name: Deploy storybook

on:
  push:
    branches: ["master", "vanilla-css", "style-x"]
  pull_request:
    branches: ["master", "vanilla-css", "style-x"]

jobs:
  deploy:
    name: Deploy storybook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
